import UIKit

public let weatherImages: [String: UIImage] = [
    "thunderstorm with light rain": UIImage(systemName: "cloud.bolt.rain")!,
    "thunderstorm with rain": UIImage(systemName: "cloud.bolt.rain")!,
    "thunderstorm with heavy rain": UIImage(systemName: "cloud.bolt.rain")!,
    "light thunderstorm": UIImage(systemName: "cloud.bolt")!,
    "thunderstorm": UIImage(systemName: "cloud.bolt")!,
    "heavy thunderstorm": UIImage(systemName: "cloud.bolt")!,
    "ragged thunderstorm": UIImage(systemName: "cloud.bolt")!,
    "thunderstorm with light drizzle": UIImage(systemName: "cloud.bolt.rain")!,
    "thunderstorm with drizzle": UIImage(systemName: "cloud.bolt.rain")!,
    "thunderstorm with heavy drizzle": UIImage(systemName: "cloud.bolt.rain")!,
    "light intensity drizzle": UIImage(systemName: "cloud.drizzle")!,
    "drizzle": UIImage(systemName: "cloud.drizzle")!,
    "heavy intensity drizzle": UIImage(systemName: "cloud.drizzle")!,
    "light intensity drizzle rain": UIImage(systemName: "cloud.drizzle")!,
    "drizzle rain": UIImage(systemName: "cloud.drizzle")!,
    "heavy intensity drizzle rain": UIImage(systemName: "cloud.drizzle")!,
    "shower rain and drizzle": UIImage(systemName: "cloud.drizzle")!,
    "heavy shower rain and drizzle": UIImage(systemName: "cloud.drizzle")!,
    "shower drizzle": UIImage(systemName: "cloud.drizzle")!,
    "light rain": UIImage(systemName: "cloud.rain")!,
    "moderate rain": UIImage(systemName: "cloud.rain")!,
    "heavy intensity rain": UIImage(systemName: "cloud.rain")!,
    "very heavy rain": UIImage(systemName: "cloud.heavyrain")!,
    "extreme rain": UIImage(systemName: "cloud.heavyrain")!,
    "freezing rain": UIImage(systemName: "cloud.sleet")!,
    "light intensity shower rain": UIImage(systemName: "cloud.drizzle")!,
    "shower rain": UIImage(systemName: "cloud.heavyrain")!,
    "heavy intensity shower rain": UIImage(systemName: "cloud.heavyrain")!,
    "ragged shower rain": UIImage(systemName: "cloud.heavyrain")!,
    "light snow": UIImage(systemName: "cloud.snow")!,
    "snow": UIImage(systemName: "cloud.snow")!,
    "heavy snow": UIImage(systemName: "cloud.snow")!,
    "sleet": UIImage(systemName: "cloud.sleet")!,
    "light shower sleet": UIImage(systemName: "cloud.sleet")!,
    "shower sleet": UIImage(systemName: "cloud.sleet")!,
    "light rain and snow": UIImage(systemName: "cloud.sleet")!,
    "rain and snow": UIImage(systemName: "cloud.sleet")!,
    "light shower snow": UIImage(systemName: "cloud.sleet")!,
    "shower snow": UIImage(systemName: "cloud.sleet")!,
    "heavy shower snow": UIImage(systemName: "cloud.sleet")!,
    "mist": UIImage(systemName: "cloud.fog")!,
    "smoke": UIImage(systemName: "cloud.fog")!,
    "haze": UIImage(systemName: "cloud.fog")!,
    "sand/dust whirls": UIImage(systemName: "cloud.fog")!,
    "fog": UIImage(systemName: "cloud.fog")!,
    "sand": UIImage(systemName: "cloud.fog")!,
    "dust": UIImage(systemName: "cloud.fog")!,
    "volcanic ash": UIImage(systemName: "cloud.fog")!,
    "squalls": UIImage(systemName: "cloud.fog")!,
    "tornado": UIImage(systemName: "tornado")!,
    "clear sky": UIImage(systemName: "sun.max")!,
    "few clouds": UIImage(systemName: "cloud.sun")!,
    "scattered clouds": UIImage(systemName: "cloud.sun")!,
    "broken clouds": UIImage(systemName: "cloud")!,
    "overcast clouds": UIImage(systemName: "smoke")!,
]
